### PR TITLE
Adds support to take snapshots from volumes

### PR DESCRIPTION
**Pull request by rafaelp**
I've implemented support to take snapshots of volumes. I had to update barge gem also.
In the README I put the instructions to install the specific version of barge.

Here are some examples of the new parameter.

Only take snapshots of droplets (default)

  $ do_snapshot -r droplets

  Only take snapshots of volumes

  $ do_snapshot --resource_types volumes

  Take snapshots of both

  $ do_snapshot -r droplets,volumes

All other parameters (--only, --exclude, --clean, etc) works for volumes as well.

### CODE REVIEW

**Comment by merqlove** [comment]
Hello, @rafaelp. Thanks ❤️❤️❤️. It looks as nice feature! 
But we need to make specs passed first.
I will review it in one day.

**Comment by merqlove** [comment]
P.S. @rafaelp , we cannot use gem references from Gemfile in production.

**Comment by rafaelp** [comment]
I know we cannot use gem reference from Gemfile, I did that because this gem is not published and I'm not the author to update it myself. There is no way to add specific commit of a git repository in gemspec
I left this way to be able to use in my own server (and I'm already using it :smile:)

**Comment by merqlove** [comment]
I'm think we must migrate to `https://github.com/digitalocean/droplet_kit` first.

**Comment by merqlove** [comment]
Backend of default v2 adapter was changed to DropletKit.
Extracted adapter shared specs for better customization.

**Comment by merqlove** [comment]
@rafaelp thanks for your PR, feel free to make additional adapter for volumes.
I think we can add Volumes logic by adapter and have commands as `resource agnostic` interface.
I like your idea to rename droplet to the resource, but won't support volumes inside commands. Adapter is better case.
I have plans to make this rebase/adapter, but on my calendar it can be after 11.17. If you want these things faster, do it.
Test covered adapter extension example is in the folder example.

**Pull request closed without merging**
